### ISSUE TITLE
Support for local ~/.aws credentials file

### ISSUE THREAD

**Issue by manugarri** [opendatadiscovery/odd-collector-aws#47]
Im trying to run a collector on docker-compose and it would be great if we could just reference the local machine ~/.aws credentials folder instead of having to hardcode the credentials on an environment file, since credentials expire after a few hours.

On docker-compose this is usually achieved like this:
  
```
odd-collector-aws:
    image: 'ghcr.io/opendatadiscovery/odd-collector-aws:latest'
    restart: always
    volumes:
      - ./config/collector_config_aws.yaml:/app/collector_config.yaml
      - "$HOME/.aws/credentials:/usr/local/airflow/.aws/credentials:ro"
    environment:
      - AWS_REGION=region_name
      - AWS_PROFILE=profile_name
 ```

However the above implementation does not seem to work.

based on what i see here https://github.com/opendatadiscovery/odd-collector-aws/blob/main/odd_collector_aws/aws/aws_client.py#L29, we are using boto3 but instead of following the standard AWS authentication workflow, we are forcing the use of the config. 

Wouldnt it make more sense to:
  - make the config.credentials optional
  - check at session creation time if the credentials exist in the config, then use them.
  - if not, then revert to default boto3.session() (which will go through the environment variables, then the local aws profile, then the ec2 instance role authentication process)
